name: "repairlink_mechanical_analytics"
config-version: 2

profile: "repairlink_mechanical_analytics"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  repairlink_mechanical_analytics:
    staging:
      +materialized: incremental
      +schema: staging

    intermediate:
      +materialized: table
      +schema: intermediate

      reference:
        +schema: reference
        +materialized: table

    final:
      +materialized: table
      +schema: final