
name: 'repairlink_mechanical_analytics'
version: '1.0.0'

profile: 'repairlink_mechanical_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  repairlink_mechanical_analytics:
    staging:
      +materialized: incremental
<<<<<<< HEAD
      +schema: STAGING

=======
      +schema: staging
>>>>>>> 87c6b998eb2b8f9fabc1b2147e626b79d6a5bd58
    intermediate:
      +materialized: table
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts
